### ISSUE TITLE
v1

### ISSUE THREAD

**Issue by eladb** [eladb/pizu#1]
### The Big Bumper

Let's build the entire bump capability as a separate open source project so other people can use it for other projects.

Basically it consists of a server and client libs (for any platform we need, _phonegap_ will probably be first...). 
The client library simply sends a payload via a request to the server and receives any payload(s?) and a session id that were sent by other devices on the same timeframe on the same geo-location. A timeout indicates that there is no bump.

Payloads should be a promised input (pass a function that calculates the payload).

Not secure and not private but I think it will work.
### Client Apps

The app requires facebook login. When logged in, it queries the graph for the user's friends list and stores it in-memory (refresh on app activation).

It starts the bump library so that when a bump occurs the list of friend IDs will be sent to the other side. The response (if not timed out) is the friend IDs of the other side and they are matched in-memory in against the local friend IDs and the common friends are displayed. Yey!
### Stack

**Frontend**: I think we should try to create the clients using phonegap/HTML and not native shit. This way we will be able to publish it in multiple platforms without too much extra work (hopefully). _What do you think?_

**Backends**: Anything that talks HTTP and does not require build, preferability node.js

**Comment by eladb** [comment]
Here's an API proposal for thebb (the big bumper) library (ala jquery):

``` js
thebb()
  .send(function()    { /* ... return friend ids ... */    })
  .bump(function(p)   { /* ... match `p` to friends ... */ })
  .timeout(function() { /* ... show error message ... */   })
```

**Comment by eladb** [comment]
@saary @leonvaidman @ramgreenberg @ShaiBer what do you think? Did I miss anything? Feel free to say if u are interested to take any part of it.

**Comment by ShaiBer** [comment]
Hey, cheers for getting things started @eladb  :) 

I think the next step should be to meet again and decide what the app will look like, the high level design and the work division between us. (off course we can also discuss here, but I prefer to interact F2F when possible, especially at the beginning when you need to brain storm)

About the API:  I think the first version can be made even simpler: if we only use FB then all you need to get from the other side is his id, not his friends' ids, and you can use FB API to discover the shared friends. Later on, my feeling is that we might be forced to perform the calculations on the server if we would like to discover connections of the third degree and above since the processing power required might be considerable and since you will need to transfer lots of ids if you will want to calculate on the client side.

BTW, if it wasn’t already obvious from the above, then I want to take part in the project :)

**Comment by ramgreenberg** [comment]
Hi all,

I agree with Shai that we should meet again in order to better define our  UX.

I have a feeling that the bump experience is already related to data transferring, and that we should find another cool 

experience for our need.

I have few ideas that I will be glad to share and brainstorm with you guys.

Let’s schedule a short meeting (Sunday? Monday? I’m quite available these days :))

Cheers and good luck,
Ram

**Comment by leonvaidman** [comment]
I prefer on Sunday (I have a flight on Monday)

**Comment by eladb** [comment]
I think we can (and should) try to discuss over mail/github instead of
meetings. We have different schedules and work habits and asynchronous
communication works much better. It does require more verbosity but it is a
lot of fun when it works and everybody cooperates
On May 12, 2012 12:05 PM, "Leon Vaidman" <
reply@reply.github.com>
wrote:

**Comment by saary** [comment]
+1 for phonegap (cordova is the next version and it added CommonJS)

For the server the most I care about is costs. It is simple enough to be written in whatever we like.

**Comment by eladb** [comment]
Suggested division of work:
- bump backend + phonegap frontend
- phonegap app client (+ fb + ui)

I would love to do any of those. Bump looks to me interesting to bundle in
the open source aspect and the phonegap client is cool because I need some
more milage on web UI/HTML5/jqmobile/shit/like/that.

@saary, you have smaller availability i am assuming, so maybe you should
think what makes sense for you to start with and we will fill in the rest.
Let's talk about a two week period.

On Sat, May 12, 2012 at 10:36 PM, Saar Yahalom <
reply@reply.github.com

> wrote:
> 
> +1 for phonegap (cordova is the next version and it added CommonJS)
> 
> For the server the most I care about is costs. It is simple enough to be
> written in whatever we like.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/eladb/pizu/issues/1#issuecomment-5671185

## 

Elad.

**Comment by saary** [comment]
I can create an Android phonegap shell project that would include:
- FB sign-in
- Load backbone.js
- Load juqery + jquery UI

The following will not be included in the first client shell and are open for the grabbing:
- The actual UI views (backbone ViewModel with jquery-ui/other-ui-framework views).
- The data layer (pure js please, if designed carefully can be done transparently by backbone.js)
- Accelometer module to detect the bump.

_if you want to run faster let me know, and I will grab whatever seems reasonable instead._

**Comment by ramgreenberg** [comment]
I think that before we start implementing lets agree on the UX.

Im not sure that the bump is the right trigger for us, there might be IP rights on it (not sure) and it is already related to data transferring.

Some alternatives:

• We can use a similar mechanism but replacing the bumping phones with bumping icons. When a user opens the application he sees his FB profile picture in the middle of the screen (the background can be a picture or something that illustrates a social network). Both users should slide their icon simultaneously towards each other (the system can pair between them by geo-location & icon movement).  When the icons bump into each other they cause a collision which reveals the way they are connected. In order to see the full network  the users  must physically combine both phones - each phone will present part of the connection network (for example: Alice and Bob have a mutual friend - Ron, when Alice and Bob perform the icon bumping. Alices screen will present her icon connected to a half of Rons icon, and Bobs screen  will present the second half of Rons icon connected to Bobs icon)

• When a user opens the application he sees his icon in the middle surrounded with many other icons – the icons belong to people who opened the application and are nearby his location.
then he chooses to bump his icon into one of the surrounding icons – this action reveals part of the network connection (the same mechanism as in the first alternative). In order to see the full network connection the other person should do the same on his phone.

Let me know what do you think ( I hope I made it clear enough :)  )

Thanks,
Ram

**Comment by eladb** [comment]
http://intellectuallylegal.wordpress.com/2011/09/04/bump-technologies-exchange-contact-info-and-other-data-with-other-people-by-tapping-your-phones-together/
On May 13, 2012 1:52 PM, "ramgreenberg" <
reply@reply.github.com>
wrote:

**Comment by saary** [comment]
I guess we will be "simultaneously broadcasting contact info and other data to nearby listeners" instead of exchanging data.

**Comment by eladb** [comment]
@ShaiBer wrote:

> About the API: I think the first version can be made even simpler: if we only use FB then all you need to get from the other side is his id, not his friends' ids, and you can use FB API to discover the shared friends. Later on, my feeling is that we might be forced to perform the calculations on the server if we would like to discover connections of the third degree and above since the processing power required might be considerable and since you will need to transfer lots of ids if you will want to calculate on the client side.

Good point. Facebook has a [mutualfriends](https://developers.facebook.com/docs/reference/api/user/#mutualfriends) attribute in the User object and we can use it. The "bumper" mechanism basically allows the client to pass along any payload it wants.

**Comment by eladb** [comment]
@ramgreenberg wrote:

> I have a feeling that the bump experience is already related to data transferring, and that we should find another cool experience for our need. I have few ideas that I will be glad to share and brainstorm with you guys.

I agree. I think we can find some crazy funny way instead of bumping the phones.
Let's try to discuss some ideas here: #2

Also, see [this comment](https://github.com/eladb/pizu/issues/2#issuecomment-5679376)

**Comment by eladb** [comment]
@saary Go ahead. Sounds awesome. I saw you already submitted some code.
